[Config]
Proxies=android.hardware.camera.provider@2.5::ICameraProvider/legacy/0
Proxies=android.hardware.camera.provider@2.5::ICameraProvider/legacy/1
Proxies=android.hardware.camera.provider@2.6::ICameraProvider/legacy/0
Proxies=android.hardware.camera.provider@2.6::ICameraProvider/legacy/1
Proxies=android.hardware.camera.provider@2.7::ICameraProvider/legacy/0
Proxies=android.hardware.camera.provider@2.7::ICameraProvider/legacy/1

CustomProperties=ro.appsupport.use_host_power=false
CustomProperties=ro.appsupport.radio_bridge=true
CustomProperties=ro.telephony.iwlan_operation_mode=legacy

[Devices]
AppSupportRadioEnabled=true

